# Generated by Django 4.1 on 2022-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=1, verbose_name='Взрослых'),
        ),
        migrations.AddField(
            model_name='booking',
            name='kids',
            field=models.IntegerField(default=0, verbose_name='Детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status_conf',
            field=models.CharField(choices=[('2', 'wait'), ('1', 'confirm'), ('3', 'cancel'), ('4', 'expire'), ('5', 'success')], default='2', max_length=1, verbose_name='Статус брони'),
        ),
    ]
