# Generated by Django 4.1 on 2022-08-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_category_name_alter_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
