# Generated by Django 4.1 on 2022-08-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_checkin_alter_room_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
