# Generated by Django 4.1 on 2022-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_room_checkin_alter_room_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slide1',
            field=models.ImageField(blank=True, null=True, upload_to='booking/img/room-slide'),
        ),
        migrations.AddField(
            model_name='room',
            name='slide2',
            field=models.ImageField(blank=True, null=True, upload_to='booking/img/room-slide'),
        ),
        migrations.AddField(
            model_name='room',
            name='slide3',
            field=models.ImageField(blank=True, null=True, upload_to='booking/img/room-slide'),
        ),
    ]
