# Generated by Django 4.1 on 2022-08-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_slide1_room_slide2_room_slide3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
