# Generated by Django 4.1 on 2022-09-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_cost_booking_nights_customuser_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_cancel',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
    ]
