# Generated by Django 4.1 on 2022-09-11 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_customuser_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_arrive',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда'),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_of_depart',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Гость'),
        ),
    ]
