# Generated by Django 4.1 on 2022-09-01 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_alter_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_book', models.DateField(auto_now_add=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('status_conf', models.CharField(choices=[('1', 'wait'), ('2', 'confirm'), ('3', 'cancel'), ('4', 'expire'), ('5', 'success')], default='1', max_length=1)),
                ('deadline_conf', models.DateField()),
                ('date_of_conf', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
