# Generated by Django 4.1 on 2022-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_date_of_arrive_booking_date_of_depart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedForEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_of_sign', models.DateField(auto_now_add=True, verbose_name='Дата подписки')),
                ('date_last_send', models.DateField(blank=True, null=True, verbose_name='Дата последней рассылки')),
            ],
            options={
                'verbose_name': 'Подписки',
            },
        ),
    ]
