# Generated by Django 4.1 on 2022-09-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_conf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deadline_conf',
            field=models.DateField(blank=True, null=True),
        ),
    ]
